use_frameworks!

platform :ios, '13.0'

target 'HashingSwift_Example' do
  pod 'HashingSwift', :path => '../'
  pod 'CommonSwift', :git => 'https://github.com/sublabdev/common-swift.git', :commit => 'fd97ff6ef1adc54be966e7d2e125127c979af68b'
  pod 'xxHash-Swift'
  pod 'Base58Swift'
  pod 'Blake2'

  target 'HashingSwift_Tests' do
    inherit! :search_paths

    
  end
end
